export const INSPIRATIONS = [
  "epic music", "abstract hip hop", "filter", "electronic piano", "électro", "goa",
  "throat singing", "finger style guitar", "soundscape", "aggressive beats", "newage",
  "minimalist piano", "reggae beat", "arabic pop", "gongs", "mantra", "synth metal",
  "electronic", "synthwave", "humming", "funk", "rap", "country", "piano",
  "complex rhythm", "acoustic metal", "motivational rap", "polyphonic", "boy group",
  "cute vocal", "female soul voice", "slow pop rock", "slow rap", "complex polyrhythms",
  "rock", "r&b", "deep heavy bass", "deep drums", "dubstep", "sexy r&b", "pop-rap",
  "atmospheric metal", "dreamy soundscapes", "crossover thrash", "intricate melody",
  "circus music", "emotional swells", "pop", "classical", "saxophones", "lo-fi",
  "afrobeat", "haunting synths", "dark cyberpunk", "deep beat", "melodic tripop",
  "liquid funk", "dark themes", "nerdcore", "pop metal", "dark rock", "dreamy synth",
  "lambada", "driving riffs", "pop rock", "delicate percussion", "minimalist production",
  "gentle strings", "indie", "soft bass", "soaring chorus", "energetic guitar riffs",
  "k-pop dance", "smooth female vocals", "light piano", "fat bass", "aggressive drums",
  "club anthem", "hip hop", "jazz", "screamed vocals", "90s grunge", "bright melody",
  "calypso", "tropical percussion", "dungeon neo soul", "sweet pop", "catchy vocals",
  "cinematic electronic", "techno", "latin", "ambient", "darkstep", "haunting female vocals",
  "carefree", "spanish rock", "vocal harmony", "trap", "chanson française",
  "epic rap", "emotional explosion", "moroccan", "bass 808", "rawstyle",
  "aggressive guitars", "lofi hip-hop", "surf rock", "alternative rock",
  "edm", "trance music", "country music", "bubblegum dance", "pluggnb",
  "live performance", "funky disco", "rock rap", "classic piano", "metal",
  "gangsta rap", "softrock", "fantasy rock", "melancholic vibe", "barbershop quartet",
  "chill jazz", "orchestral elements", "melodic rap", "ambient electronic",
  "uplifting melody", "atmospheric soundscape", "house beats", "dance pop",
  "show tunes", "vibrant percussion", "playful melodies", "punk", "k-pop",
  "soaring choruses", "zouk", "disco funk", "contemporary ballad",
  "ethereal harmonies", "dark cinematic", "cinematic pads", "euphoric drops",
  "bass music", "west coast rap", "contemporary country", "urban beats",
  "groovy basslines", "infectious melodies", "synth layers", "slow reggae",
  "rock funk", "rock'n'roll", "variété française", "summer song",
  "mississippi delta blues", "edm-pop", "video game music", "fusion",
  "dreamy female vocals", "synthwave", "greek folk", "guitar solo",
  "hardcore", "chill r&b", "progressive electronic", "a cappella",
  "cinematic crescendos", "cloud rap", "oldschool rap", "african choir",
  "smooth groove", "reggae", "romantic music", "soul pop", "synth pad",
  "gentle piano", "disco music", "epic chorus", "soulful rnb",
  "dancehall reggae", "tabla", "classic pop", "heavy 808 bass",
  "phonk house", "polka", "acid house", "dream-pop", "electronic percussion",
  "samba rock", "blackgaze", "indie rock", "g funk", "melbourne bounce",
  "contemporary jazz", "trap hip hop", "autotune vocals", "melodic hardcore punk",
  "regional mexicano", "deep atmosphere", "hypnotic layers", "neofolk",
  "pop house", "hybrid trap", "rock-opera", "gritty rap",
  "melodic piano", "soft r&b", "emotional trance", "synth-pop",
  "edm drops", "free jazz", "mellow beats", "melancholic piano",
  "melodic dubstep", "operatic metal", "epic ballad", "rock ballad",
  "nu-disco", "electronic rock", "progressive edm", "progressive house",
  "baroque hip hop", "power bass", "party vibes",
];
